import imgMovie from '../../../assets/img/product-landingPage.jpg';

export const movies = [
  {
    tag: "HOT",
    title: "Grave of the Fireflies",
    description: "Một câu chuyện cảm động về hai anh em trong chiến tranh Nhật Bản, đấu tranh để sinh tồn giữa sự tàn khốc của chiến tranh.",
    genre: "Drama",
    duration: 89,
    releaseDate: "1988-04-16",
    director: "Isao Takahata",
    actors: "Tsutomu Tatsumi, Ayano Shiraishi",
    imgSrc: imgMovie,
    slug: "grave-of-the-fireflies",
  },
  {
    tag: "NEW",
    title: "Your Name",
    description: "Hai thiếu niên hoán đổi thân xác và dần phát hiện ra mối liên kết kỳ lạ giữa họ.",
    genre: "Romance, Fantasy",
    duration: 106,
    releaseDate: "2016-08-26",
    director: "Makoto Shinkai",
    actors: "Ryunosuke Kamiki, Mone Kamishiraishi",
    imgSrc: imgMovie,
    slug: "your-name",
  },
  {
    title: "Spirited Away",
    description: "Cô bé Chihiro lạc vào thế giới linh hồn và phải tìm cách cứu cha mẹ mình.",
    genre: "Adventure, Fantasy",
    duration: 125,
    releaseDate: "2001-07-20",
    director: "Hayao Miyazaki",
    actors: "Rumi Hiiragi, Miyu Irino",
    imgSrc: imgMovie,
    slug: "spirited-away",
  },
  {
    title: "Weathering With You",
    description: "Một cậu bé bỏ nhà lên Tokyo và gặp một cô gái có khả năng điều khiển thời tiết.",
    genre: "Drama, Fantasy",
    duration: 112,
    releaseDate: "2019-07-19",
    director: "Makoto Shinkai",
    actors: "Kotaro Daigo, Nana Mori",
    imgSrc: imgMovie,
    slug: "weathering-with-you",
  },
];